name: ng2-dart-pagination
version: 0.0.1
description: >
  Pagination for Angular2 Dart
author: Louis Laagland <louis@wunderful.nl>
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  browser: '^0.10.0'
  angular2: '^2.0.0-beta.0'
  dart_to_js_script_rewriter: ^0.1.0
dev_dependencies:
  test: '>=0.6.0 <0.13.0'
transformers:
- angular2:
    entry_points: web/index.dart
- dart_to_js_script_rewriter
- $dart2js:
    environment:
      PROD: "true"